spring:
  data:
    solr:
      host: http://39.96.55.109:8983/solr
  datasource:
    username: root
    password: 123456
#    url: jdbc:mysql://127.0.0.1:3306/travel
    url: jdbc:mysql://39.96.55.109:3306/travel?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    #   数据源其他配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

#前端页面表单输入数据较多，包含多个文本、多张图片，在数据未压缩的情况下，最终上传失败。
  profiles:
    active: dev
    server:
      tomcat:
        max-http-post-size: -1



mybatis:
  config-location: classpath:mybatis/mybatis-config.xml  #全局配置文件的位置
  mapper-locations: classpath:mybatis/mapper/*.xml #mapper映射文件

pagehelper:
  helper-dialect: mysql
  reasonable: true  #启用合理化时，如果pageNum<1会查询第一页，如果pageNum>总页数会查询最后一页
  support-methods-arguments: true #支持通过Mapper接口参数来传递分页参数，默认值false,分页插件会从查询方法的参数值中，自动根据上面 params 配置的字段中取值，查找到合适的值时就会自动分页


